#!/usr/bin/env python3
""" perform install jupyterlab-citation-manager

    On Binder, this will run _after_ the environment has been fully created from
    the environment.yml in this directory.

    This script should also run locally on Linux/MacOS/Windows:

        python3 binder/postBuild
"""
import subprocess
import sys
from pathlib import Path


ROOT = Path.cwd()


def _(*args, **kwargs):
    """ Run a command, echoing the args

        fails hard if something goes wrong
    """
    print("\n\t", " ".join(args), "\n")
    return_code = subprocess.call(args, **kwargs)
    if return_code != 0:
        print("\nERROR", return_code, " ".join(args))
        sys.exit(return_code)


# install the labextension
_(sys.executable, "-m", "pip", "install", "jupyterlab-citation-manager")

print("JupyterLab with jupyterlab-citation-manager is ready to run with:\n")
print("\tjupyter lab\n")
